on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

name: "Stable Tag"

jobs:
  release:
    name: Create Release

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release create \
            --repo ${{ github.repository }} \
            --title ${{ github.ref_name }} \
            --generate-notes \
            ${{ github.ref_name }}

  build:
    name: "Build"

    needs: ["release"]

    uses: ./.github/workflows/part_build.yml
    with:
      releaseName: "${{ github.ref_name }}"

  docs:
    name: "Docs"

    needs: ["release"]

    uses: ./.github/workflows/part_docs.yml
    with:
      releaseName: "${{ github.ref_name }}"
